name: voyage_smart
description: "Application mobile de réservation malienne"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.20.2
  intl_utils: ^2.8.11
  geolocator: ^14.0.2
  geocoding: ^4.0.0
  http: ^1.4.0
  url_launcher: ^6.1.10
  cupertino_icons: ^1.0.8
  google_maps_flutter: ^2.6.0
  flutter_map: ^8.2.1
  latlong2: ^0.9.1
  flutter_svg: ^2.0.7
  qr_flutter: ^4.1.0
  screenshot: ^3.0.0
  path_provider: ^2.1.5
  share_plus: ^7.2.1
  image_gallery_saver_plus: ^4.0.1
  flutter_osm_plugin: ^1.4.1
  font_awesome_flutter: ^10.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

# ✅ Cette section doit être à la racine (PAS sous `flutter:`)
flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/logo_vsmart.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo_vsmart.png
    - assets/images/air_niono_logo.jpg
    - assets/images/diarra_logo.jpg
    - assets/images/nour_logo.jpg
    - assets/images/rimbo_logo.jpg
    - assets/images/sonef_logo.jpg
    - assets/icon/logo_vsmart.png
